name: Actions Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test